/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/AuthScreen` | `/AuthScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/ProfileGate` | `/ProfileGate`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TimerScreen.styles` | `/TimerScreen.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TimerScreen` | `/TimerScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/handle/AuthHandle`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useAuth`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useAuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useProfiles`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useRealTimeTimer`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useTimer`; params?: Router.UnknownInputParams; } | { pathname: `/test/useRealTimeTimer.test`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/types`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/AuthScreen` | `/AuthScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/ProfileGate` | `/ProfileGate`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/TimerScreen.styles` | `/TimerScreen.styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/TimerScreen` | `/TimerScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/handle/AuthHandle`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useAuth`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useAuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useProfiles`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useRealTimeTimer`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useTimer`; params?: Router.UnknownOutputParams; } | { pathname: `/test/useRealTimeTimer.test`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/types${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/AuthScreen${`?${string}` | `#${string}` | ''}` | `/AuthScreen${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/ProfileGate${`?${string}` | `#${string}` | ''}` | `/ProfileGate${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/TimerScreen.styles${`?${string}` | `#${string}` | ''}` | `/TimerScreen.styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/TimerScreen${`?${string}` | `#${string}` | ''}` | `/TimerScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/context/AuthContext${`?${string}` | `#${string}` | ''}` | `/handle/AuthHandle${`?${string}` | `#${string}` | ''}` | `/hooks/useAuth${`?${string}` | `#${string}` | ''}` | `/hooks/useAuthContext${`?${string}` | `#${string}` | ''}` | `/hooks/useProfiles${`?${string}` | `#${string}` | ''}` | `/hooks/useRealTimeTimer${`?${string}` | `#${string}` | ''}` | `/hooks/useTimer${`?${string}` | `#${string}` | ''}` | `/test/useRealTimeTimer.test${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/AuthScreen` | `/AuthScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/ProfileGate` | `/ProfileGate`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TimerScreen.styles` | `/TimerScreen.styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TimerScreen` | `/TimerScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/handle/AuthHandle`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useAuth`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useAuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useProfiles`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useRealTimeTimer`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useTimer`; params?: Router.UnknownInputParams; } | { pathname: `/test/useRealTimeTimer.test`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
